CREATE TABLE pais (
	idpais SERIAL, 
	nome CHARACTER VARYING(100) NOT NULL
);

INSERT INTO pais(nome) VALUES('BRASIL');

CREATE TABLE usuario (
	idusuario SERIAL, 
	nome CHARACTER VARYING(100) NOT NULL,
	email CHARACTER VARYING(100) UNIQUE NOT NULL,
  senha CHARACTER VARYING(100) NOT NULL
);
